// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/timer/api/v1/app/create": {
            "post": {
                "description": "创建应用",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "应用相关接口"
                ],
                "summary": "创建应用",
                "parameters": [
                    {
                        "description": "创建定时器定义",
                        "name": "def",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateAppDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.WebRsp"
                        }
                    }
                }
            }
        },
        "/timer/api/v1/app/deleteApp": {
            "delete": {
                "description": "删除app",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "应用相关接口"
                ],
                "summary": "删除app",
                "parameters": [
                    {
                        "description": "删除APP",
                        "name": "def",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteAppDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/constants.WebRsp"
                        }
                    }
                }
            }
        },
        "/timer/api/v1/app/list": {
            "get": {
                "description": "查询 App 列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "应用相关接口"
                ],
                "summary": "查询 App 列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "创建人",
                        "name": "creator",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "应用名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "分页序号",
                        "name": "page_index",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "分页大小",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "sorted_by",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.WebRsp"
                        }
                    }
                }
            }
        },
        "/timer/api/v1/def/change": {
            "post": {
                "description": "改变定时器状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "定时器相关接口"
                ],
                "summary": "改变定时器状态",
                "parameters": [
                    {
                        "description": "修改定时器状态",
                        "name": "def",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ChangeTimerStatusDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.WebRsp"
                        }
                    }
                }
            }
        },
        "/timer/api/v1/def/create": {
            "post": {
                "description": "创建定时器定义",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "定时器相关接口"
                ],
                "summary": "创建定时器定义",
                "parameters": [
                    {
                        "description": "创建定时器定义",
                        "name": "def",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateTimerDefDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.WebRsp"
                        }
                    }
                }
            }
        },
        "/timer/api/v1/def/delete": {
            "delete": {
                "description": "删除定时器",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "定时器相关接口"
                ],
                "summary": "删除定时器",
                "parameters": [
                    {
                        "type": "string",
                        "name": "app",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "def_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.WebRsp"
                        }
                    }
                }
            }
        },
        "/timer/api/v1/def/deleteRunHistories": {
            "delete": {
                "description": "删除过期历史执行记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "定时器相关接口"
                ],
                "summary": "删除过期历史执行记录",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/constants.WebRsp"
                        }
                    }
                }
            }
        },
        "/timer/api/v1/def/get": {
            "get": {
                "description": "查询单条定时器定义",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "定时器相关接口"
                ],
                "summary": "查询单条定时器定义",
                "parameters": [
                    {
                        "type": "string",
                        "description": "[必填] 主键ID",
                        "name": "def_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.WebRsp"
                        }
                    }
                }
            }
        },
        "/timer/api/v1/def/list": {
            "get": {
                "description": "分页查询定时器列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "定时器相关接口"
                ],
                "summary": "分页查询定时器列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "[必填] APP 应用名",
                        "name": "app",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "创建人",
                        "name": "creator",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "定时器名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "分页序号",
                        "name": "page_index",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "分页大小",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "sorted_by",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.WebRsp"
                        }
                    }
                }
            }
        },
        "/timer/api/v1/def/runHistory": {
            "get": {
                "description": "获取定时器运行历史记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "定时器相关接口"
                ],
                "summary": "获取定时器运行历史记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "[必填] APP 应用名",
                        "name": "app",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "创建人",
                        "name": "creator",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "定时器名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "分页序号",
                        "name": "page_index",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "分页大小",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "sorted_by",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.WebRsp"
                        }
                    }
                }
            }
        },
        "/timer/api/v1/def/timerListSend": {
            "post": {
                "description": "定时器列表批量触发",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "定时器相关接口"
                ],
                "summary": "定时器列表批量触发",
                "parameters": [
                    {
                        "description": "定时器列表批量触发",
                        "name": "def",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.TimerListSendNotifyDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.WebRsp"
                        }
                    }
                }
            }
        },
        "/timer/api/v1/def/timerTaskList": {
            "get": {
                "description": "获取定时器任务列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "定时器相关接口"
                ],
                "summary": "获取定时器任务列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "结束时间 时间戳格式 \"2021-01-01 01:01\"",
                        "name": "end_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "开始时间 时间戳格式 \"2021-01-01 01:01\"",
                        "name": "start_time",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.WebRsp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "constants.WebRsp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object"
                },
                "message": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.ChangeTimerStatusDTO": {
            "type": "object",
            "required": [
                "def_id",
                "status"
            ],
            "properties": {
                "def_id": {
                    "description": "[必填] 主键ID",
                    "type": "string"
                },
                "status": {
                    "description": "[必填] 定时器定义状态 1:激活, 2:去激活",
                    "type": "integer"
                }
            }
        },
        "dto.CreateAppDTO": {
            "type": "object",
            "properties": {
                "creator": {
                    "description": "创建人",
                    "type": "string"
                },
                "name": {
                    "description": "应用名称",
                    "type": "string"
                }
            }
        },
        "dto.CreateTimerDefDTO": {
            "type": "object",
            "required": [
                "app",
                "creator",
                "name",
                "notify_type",
                "timer_type"
            ],
            "properties": {
                "app": {
                    "description": "[必填] APP 应用名",
                    "type": "string"
                },
                "creator": {
                    "description": "[必填] 创建人",
                    "type": "string"
                },
                "cron": {
                    "description": "定时器定时配置",
                    "type": "string"
                },
                "def_id": {
                    "description": "主键ID",
                    "type": "string"
                },
                "delay_time": {
                    "description": "延时定时器触发时间 格式为:\"2006-01-02 15:04:05\"",
                    "type": "string"
                },
                "delete_type": {
                    "description": "自动删除机制 0-不删除 1-删除",
                    "type": "integer"
                },
                "end_time": {
                    "description": "定时器停止时间 格式为:\"2006-01-02 15:04:05\"",
                    "type": "string"
                },
                "execute_time_limit": {
                    "description": "任务单次执行时间限制，单位：s. 默认 15 s.",
                    "type": "integer"
                },
                "name": {
                    "description": "[必填] 定时器名称",
                    "type": "string"
                },
                "notify_http_param": {
                    "description": "Http 回调参数",
                    "$ref": "#/definitions/dto.NotifyHttpParam"
                },
                "notify_rpc_param": {
                    "description": "Rpc  回调参数",
                    "$ref": "#/definitions/dto.NotifyRpcParam"
                },
                "notify_type": {
                    "description": "[必填] 通知类型 1:rpc 2:kafka",
                    "type": "integer"
                },
                "status": {
                    "description": "定时器定义状态，1:激活, 2:未激活",
                    "type": "integer"
                },
                "timer_type": {
                    "description": "[必填] 定时器类型 1：延时定时器 2：cron定时器",
                    "type": "integer"
                },
                "trigger_type": {
                    "description": "触发类型 1-触发一次 2-持续触发",
                    "type": "integer"
                }
            }
        },
        "dto.DeleteAppDTO": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "应用名称",
                    "type": "string"
                }
            }
        },
        "dto.NotifyHttpParam": {
            "type": "object",
            "properties": {
                "body": {
                    "description": "参数体",
                    "type": "string"
                },
                "header": {
                    "description": "header 请求头",
                    "type": "string"
                },
                "method": {
                    "description": "POST,GET 方法",
                    "type": "string"
                },
                "url": {
                    "description": "URL 路径",
                    "type": "string"
                }
            }
        },
        "dto.NotifyRpcParam": {
            "type": "object",
            "properties": {
                "callee_env": {
                    "description": "callee 被调服务环境",
                    "type": "string"
                },
                "method": {
                    "description": "回调方法名",
                    "type": "string"
                },
                "params": {
                    "description": "回调参数",
                    "type": "string"
                },
                "rpc_name": {
                    "description": "对应 method 别名，优先使用 RpcName 寻址",
                    "type": "string"
                },
                "service": {
                    "description": "服务名:对应 123 平台上 service.name",
                    "type": "string"
                }
            }
        },
        "dto.TimerListSendNotifyDTO": {
            "type": "object",
            "properties": {
                "timer_list": {
                    "description": "定时器列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "web.WebRsp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
