// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: timer_endpoint.proto

package timer

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// CreateTimerReq 创建定时器
type CreateTimerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicReq         *BasicReq        `protobuf:"bytes,1,opt,name=basic_req,json=basicReq,proto3" json:"basic_req,omitempty"`
	Name             string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                     // [必填] 定时器名称
	Creator          string           `protobuf:"bytes,3,opt,name=creator,proto3" json:"creator,omitempty"`                                               // [必填] 创建者
	App              string           `protobuf:"bytes,4,opt,name=app,proto3" json:"app,omitempty"`                                                       // [必填] 应用名
	Cron             string           `protobuf:"bytes,5,opt,name=cron,proto3" json:"cron,omitempty"`                                                     // [选填] 定时器定时配置
	NotifyType       uint32           `protobuf:"varint,6,opt,name=notify_type,json=notifyType,proto3" json:"notify_type,omitempty"`                      // [必填] 通知类型 1:rpc 2:kafka
	TimerType        uint32           `protobuf:"varint,7,opt,name=timer_type,json=timerType,proto3" json:"timer_type,omitempty"`                         // [必填] 定时器类型 1：延时定时器 2：cron定时器
	DelayTime        string           `protobuf:"bytes,8,opt,name=delay_time,json=delayTime,proto3" json:"delay_time,omitempty"`                          // [选填] 延时定时器触发时间 格式为:"2006-01-02 15:04:05"
	NotifyRpcParam   *NotifyRpcParam  `protobuf:"bytes,9,opt,name=notify_rpc_param,json=notifyRpcParam,proto3" json:"notify_rpc_param,omitempty"`         // [选填] RPC 调用参数
	NotifyHttpParam  *NotifyHttpParam `protobuf:"bytes,10,opt,name=notify_http_param,json=notifyHttpParam,proto3" json:"notify_http_param,omitempty"`     // [选填] HTTP 调用参数
	EndTime          string           `protobuf:"bytes,11,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`                               // [必填] 结束时间 格式为 "2006-01-02 15:04:05"
	TriggerType      uint32           `protobuf:"varint,12,opt,name=trigger_type,json=triggerType,proto3" json:"trigger_type,omitempty"`                  // [必填] 触发类型 1:触发一次 2:持续触发
	DeleteType       uint32           `protobuf:"varint,13,opt,name=delete_type,json=deleteType,proto3" json:"delete_type,omitempty"`                     // [选填] 自动删除机制 0-不删除 1-删除
	ExecuteTimeLimit int32            `protobuf:"varint,14,opt,name=execute_time_limit,json=executeTimeLimit,proto3" json:"execute_time_limit,omitempty"` // [选填] 定时任务单次执行时间限制，范围为 0 ~ 15, 单位：s. 默认 15 s.
}

func (x *CreateTimerReq) Reset() {
	*x = CreateTimerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endpoint_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTimerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTimerReq) ProtoMessage() {}

func (x *CreateTimerReq) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTimerReq.ProtoReflect.Descriptor instead.
func (*CreateTimerReq) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTimerReq) GetBasicReq() *BasicReq {
	if x != nil {
		return x.BasicReq
	}
	return nil
}

func (x *CreateTimerReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTimerReq) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *CreateTimerReq) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *CreateTimerReq) GetCron() string {
	if x != nil {
		return x.Cron
	}
	return ""
}

func (x *CreateTimerReq) GetNotifyType() uint32 {
	if x != nil {
		return x.NotifyType
	}
	return 0
}

func (x *CreateTimerReq) GetTimerType() uint32 {
	if x != nil {
		return x.TimerType
	}
	return 0
}

func (x *CreateTimerReq) GetDelayTime() string {
	if x != nil {
		return x.DelayTime
	}
	return ""
}

func (x *CreateTimerReq) GetNotifyRpcParam() *NotifyRpcParam {
	if x != nil {
		return x.NotifyRpcParam
	}
	return nil
}

func (x *CreateTimerReq) GetNotifyHttpParam() *NotifyHttpParam {
	if x != nil {
		return x.NotifyHttpParam
	}
	return nil
}

func (x *CreateTimerReq) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *CreateTimerReq) GetTriggerType() uint32 {
	if x != nil {
		return x.TriggerType
	}
	return 0
}

func (x *CreateTimerReq) GetDeleteType() uint32 {
	if x != nil {
		return x.DeleteType
	}
	return 0
}

func (x *CreateTimerReq) GetExecuteTimeLimit() int32 {
	if x != nil {
		return x.ExecuteTimeLimit
	}
	return 0
}

// NotifyRpcParam RPC 调用参数
type NotifyRpcParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service   string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`                      // [必填]服务名:对应 123 平台上 service.name
	Method    string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`                        // [必填]回调方法名
	RpcName   string `protobuf:"bytes,3,opt,name=rpc_name,json=rpcName,proto3" json:"rpc_name,omitempty"`       // [必填]对应 method 别名，优先使用 RpcName 寻址
	Params    string `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`                        // [必填]回调参数
	CalleeEnv string `protobuf:"bytes,5,opt,name=callee_env,json=calleeEnv,proto3" json:"callee_env,omitempty"` // [必填]被调服务环境
}

func (x *NotifyRpcParam) Reset() {
	*x = NotifyRpcParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endpoint_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyRpcParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRpcParam) ProtoMessage() {}

func (x *NotifyRpcParam) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRpcParam.ProtoReflect.Descriptor instead.
func (*NotifyRpcParam) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{1}
}

func (x *NotifyRpcParam) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *NotifyRpcParam) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *NotifyRpcParam) GetRpcName() string {
	if x != nil {
		return x.RpcName
	}
	return ""
}

func (x *NotifyRpcParam) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

func (x *NotifyRpcParam) GetCalleeEnv() string {
	if x != nil {
		return x.CalleeEnv
	}
	return ""
}

type CreateTimerRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicRsp *BasicRsp `protobuf:"bytes,1,opt,name=basic_rsp,json=basicRsp,proto3" json:"basic_rsp,omitempty"`
	Data     string    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateTimerRsp) Reset() {
	*x = CreateTimerRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endpoint_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTimerRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTimerRsp) ProtoMessage() {}

func (x *CreateTimerRsp) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTimerRsp.ProtoReflect.Descriptor instead.
func (*CreateTimerRsp) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTimerRsp) GetBasicRsp() *BasicRsp {
	if x != nil {
		return x.BasicRsp
	}
	return nil
}

func (x *CreateTimerRsp) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// EnableTimerReq 激活定时器
type EnableTimerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicReq *BasicReq `protobuf:"bytes,1,opt,name=basic_req,json=basicReq,proto3" json:"basic_req,omitempty"`
	DefId    string    `protobuf:"bytes,2,opt,name=def_id,json=defId,proto3" json:"def_id,omitempty"` // [必填] 定时器定义ID
}

func (x *EnableTimerReq) Reset() {
	*x = EnableTimerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endpoint_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnableTimerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableTimerReq) ProtoMessage() {}

func (x *EnableTimerReq) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableTimerReq.ProtoReflect.Descriptor instead.
func (*EnableTimerReq) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{3}
}

func (x *EnableTimerReq) GetBasicReq() *BasicReq {
	if x != nil {
		return x.BasicReq
	}
	return nil
}

func (x *EnableTimerReq) GetDefId() string {
	if x != nil {
		return x.DefId
	}
	return ""
}

type EnableTimerRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicRsp *BasicRsp `protobuf:"bytes,1,opt,name=basic_rsp,json=basicRsp,proto3" json:"basic_rsp,omitempty"`
}

func (x *EnableTimerRsp) Reset() {
	*x = EnableTimerRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endpoint_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnableTimerRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableTimerRsp) ProtoMessage() {}

func (x *EnableTimerRsp) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableTimerRsp.ProtoReflect.Descriptor instead.
func (*EnableTimerRsp) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{4}
}

func (x *EnableTimerRsp) GetBasicRsp() *BasicRsp {
	if x != nil {
		return x.BasicRsp
	}
	return nil
}

// DisableTimerReq 去激活定时器
type DisableTimerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicReq *BasicReq `protobuf:"bytes,1,opt,name=basic_req,json=basicReq,proto3" json:"basic_req,omitempty"`
	DefId    string    `protobuf:"bytes,2,opt,name=def_id,json=defId,proto3" json:"def_id,omitempty"` // [必填] 定时器定义ID
}

func (x *DisableTimerReq) Reset() {
	*x = DisableTimerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endpoint_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisableTimerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableTimerReq) ProtoMessage() {}

func (x *DisableTimerReq) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableTimerReq.ProtoReflect.Descriptor instead.
func (*DisableTimerReq) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{5}
}

func (x *DisableTimerReq) GetBasicReq() *BasicReq {
	if x != nil {
		return x.BasicReq
	}
	return nil
}

func (x *DisableTimerReq) GetDefId() string {
	if x != nil {
		return x.DefId
	}
	return ""
}

type DisableTimerRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicRsp *BasicRsp `protobuf:"bytes,1,opt,name=basic_rsp,json=basicRsp,proto3" json:"basic_rsp,omitempty"`
}

func (x *DisableTimerRsp) Reset() {
	*x = DisableTimerRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endpoint_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisableTimerRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableTimerRsp) ProtoMessage() {}

func (x *DisableTimerRsp) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableTimerRsp.ProtoReflect.Descriptor instead.
func (*DisableTimerRsp) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{6}
}

func (x *DisableTimerRsp) GetBasicRsp() *BasicRsp {
	if x != nil {
		return x.BasicRsp
	}
	return nil
}

// GetTimerDefReq 获取定时器定义
type GetTimerDefReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicReq *BasicReq `protobuf:"bytes,1,opt,name=basic_req,json=basicReq,proto3" json:"basic_req,omitempty"`
	DefId    string    `protobuf:"bytes,2,opt,name=def_id,json=defId,proto3" json:"def_id,omitempty"` // [必填] 定时器定义ID
}

func (x *GetTimerDefReq) Reset() {
	*x = GetTimerDefReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endpoint_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTimerDefReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimerDefReq) ProtoMessage() {}

func (x *GetTimerDefReq) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimerDefReq.ProtoReflect.Descriptor instead.
func (*GetTimerDefReq) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{7}
}

func (x *GetTimerDefReq) GetBasicReq() *BasicReq {
	if x != nil {
		return x.BasicReq
	}
	return nil
}

func (x *GetTimerDefReq) GetDefId() string {
	if x != nil {
		return x.DefId
	}
	return ""
}

// GetTimerDefRsp 获取定时器定义返回
type GetTimerDefRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicRsp *BasicRsp `protobuf:"bytes,1,opt,name=basic_rsp,json=basicRsp,proto3" json:"basic_rsp,omitempty"`
	TimerDef *TimerDef `protobuf:"bytes,2,opt,name=timer_def,json=timerDef,proto3" json:"timer_def,omitempty"`
}

func (x *GetTimerDefRsp) Reset() {
	*x = GetTimerDefRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endpoint_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTimerDefRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimerDefRsp) ProtoMessage() {}

func (x *GetTimerDefRsp) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimerDefRsp.ProtoReflect.Descriptor instead.
func (*GetTimerDefRsp) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{8}
}

func (x *GetTimerDefRsp) GetBasicRsp() *BasicRsp {
	if x != nil {
		return x.BasicRsp
	}
	return nil
}

func (x *GetTimerDefRsp) GetTimerDef() *TimerDef {
	if x != nil {
		return x.TimerDef
	}
	return nil
}

// DeleteTimerDefReq 删除定时器定义
type DeleteTimerDefReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicReq *BasicReq `protobuf:"bytes,1,opt,name=basic_req,json=basicReq,proto3" json:"basic_req,omitempty"`
	DefId    string    `protobuf:"bytes,2,opt,name=def_id,json=defId,proto3" json:"def_id,omitempty"` // [必填] 定时器定义ID
	App      string    `protobuf:"bytes,3,opt,name=app,proto3" json:"app,omitempty"`                  // 定时器应用名称
	Name     string    `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`                // 定时器名称
}

func (x *DeleteTimerDefReq) Reset() {
	*x = DeleteTimerDefReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endpoint_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTimerDefReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTimerDefReq) ProtoMessage() {}

func (x *DeleteTimerDefReq) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTimerDefReq.ProtoReflect.Descriptor instead.
func (*DeleteTimerDefReq) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteTimerDefReq) GetBasicReq() *BasicReq {
	if x != nil {
		return x.BasicReq
	}
	return nil
}

func (x *DeleteTimerDefReq) GetDefId() string {
	if x != nil {
		return x.DefId
	}
	return ""
}

func (x *DeleteTimerDefReq) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *DeleteTimerDefReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteTimerDefRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicRsp *BasicRsp `protobuf:"bytes,1,opt,name=basic_rsp,json=basicRsp,proto3" json:"basic_rsp,omitempty"`
}

func (x *DeleteTimerDefRsp) Reset() {
	*x = DeleteTimerDefRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endpoint_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTimerDefRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTimerDefRsp) ProtoMessage() {}

func (x *DeleteTimerDefRsp) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTimerDefRsp.ProtoReflect.Descriptor instead.
func (*DeleteTimerDefRsp) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteTimerDefRsp) GetBasicRsp() *BasicRsp {
	if x != nil {
		return x.BasicRsp
	}
	return nil
}

type TimerDef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DefId          string          `protobuf:"bytes,1,opt,name=def_id,json=defId,proto3" json:"def_id,omitempty"`                              // [必填] 定时器定义ID
	Name           string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                             // [必填] 定时器名称
	Creator        string          `protobuf:"bytes,3,opt,name=creator,proto3" json:"creator,omitempty"`                                       // [必填] 创建者
	Cron           string          `protobuf:"bytes,4,opt,name=cron,proto3" json:"cron,omitempty"`                                             // [选填] 定时器定时配置
	NotifyType     uint32          `protobuf:"varint,5,opt,name=notify_type,json=notifyType,proto3" json:"notify_type,omitempty"`              // [必填] 通知类型 1:rpc 2:kafka
	TimerType      uint32          `protobuf:"varint,6,opt,name=timer_type,json=timerType,proto3" json:"timer_type,omitempty"`                 // [必填] 定时器类型 1：延时定时器 2：cron定时器
	DelayTime      string          `protobuf:"bytes,7,opt,name=delay_time,json=delayTime,proto3" json:"delay_time,omitempty"`                  // [选填] 延时定时器触发时间 格式为:"2006-01-02 15:04:05"
	NotifyRpcParam *NotifyRpcParam `protobuf:"bytes,8,opt,name=notify_rpc_param,json=notifyRpcParam,proto3" json:"notify_rpc_param,omitempty"` // [选填] RPC 调用参数
	EndTime        string          `protobuf:"bytes,9,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`                        // 截止日期
	Status         uint32          `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`                                       // 当前状态 1:未激活, 2:已激活
}

func (x *TimerDef) Reset() {
	*x = TimerDef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endpoint_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimerDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerDef) ProtoMessage() {}

func (x *TimerDef) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerDef.ProtoReflect.Descriptor instead.
func (*TimerDef) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{11}
}

func (x *TimerDef) GetDefId() string {
	if x != nil {
		return x.DefId
	}
	return ""
}

func (x *TimerDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TimerDef) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *TimerDef) GetCron() string {
	if x != nil {
		return x.Cron
	}
	return ""
}

func (x *TimerDef) GetNotifyType() uint32 {
	if x != nil {
		return x.NotifyType
	}
	return 0
}

func (x *TimerDef) GetTimerType() uint32 {
	if x != nil {
		return x.TimerType
	}
	return 0
}

func (x *TimerDef) GetDelayTime() string {
	if x != nil {
		return x.DelayTime
	}
	return ""
}

func (x *TimerDef) GetNotifyRpcParam() *NotifyRpcParam {
	if x != nil {
		return x.NotifyRpcParam
	}
	return nil
}

func (x *TimerDef) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *TimerDef) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// GetTimerDefList 获取定时器列表
type GetTimerDefListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicReq *BasicReq `protobuf:"bytes,1,opt,name=basic_req,json=basicReq,proto3" json:"basic_req,omitempty"`
	Name     string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`       //  [选填] 定时器名称
	Creator  string    `protobuf:"bytes,3,opt,name=creator,proto3" json:"creator,omitempty"` // [选填] 创建者
}

func (x *GetTimerDefListReq) Reset() {
	*x = GetTimerDefListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endpoint_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTimerDefListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimerDefListReq) ProtoMessage() {}

func (x *GetTimerDefListReq) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimerDefListReq.ProtoReflect.Descriptor instead.
func (*GetTimerDefListReq) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{12}
}

func (x *GetTimerDefListReq) GetBasicReq() *BasicReq {
	if x != nil {
		return x.BasicReq
	}
	return nil
}

func (x *GetTimerDefListReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetTimerDefListReq) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

type GetTimerDefListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicRsp  *BasicRsp   `protobuf:"bytes,1,opt,name=basic_rsp,json=basicRsp,proto3" json:"basic_rsp,omitempty"`
	TimerDefs []*TimerDef `protobuf:"bytes,2,rep,name=timer_defs,json=timerDefs,proto3" json:"timer_defs,omitempty"`
}

func (x *GetTimerDefListRsp) Reset() {
	*x = GetTimerDefListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endpoint_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTimerDefListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimerDefListRsp) ProtoMessage() {}

func (x *GetTimerDefListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimerDefListRsp.ProtoReflect.Descriptor instead.
func (*GetTimerDefListRsp) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{13}
}

func (x *GetTimerDefListRsp) GetBasicRsp() *BasicRsp {
	if x != nil {
		return x.BasicRsp
	}
	return nil
}

func (x *GetTimerDefListRsp) GetTimerDefs() []*TimerDef {
	if x != nil {
		return x.TimerDefs
	}
	return nil
}

// GetRunHistoryListReq 获取定时器执行列表
type GetRunHistoryListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicReq  *BasicReq `protobuf:"bytes,1,opt,name=basic_req,json=basicReq,proto3" json:"basic_req,omitempty"`
	DefId     string    `protobuf:"bytes,2,opt,name=def_id,json=defId,proto3" json:"def_id,omitempty"`              // [必填] 定时器定义ID
	AscOrder  bool      `protobuf:"varint,3,opt,name=asc_order,json=ascOrder,proto3" json:"asc_order,omitempty"`    // 是否升序
	PageIndex int32     `protobuf:"varint,4,opt,name=page_index,json=pageIndex,proto3" json:"page_index,omitempty"` //
	PageSize  int32     `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`    //
}

func (x *GetRunHistoryListReq) Reset() {
	*x = GetRunHistoryListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endpoint_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRunHistoryListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunHistoryListReq) ProtoMessage() {}

func (x *GetRunHistoryListReq) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunHistoryListReq.ProtoReflect.Descriptor instead.
func (*GetRunHistoryListReq) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{14}
}

func (x *GetRunHistoryListReq) GetBasicReq() *BasicReq {
	if x != nil {
		return x.BasicReq
	}
	return nil
}

func (x *GetRunHistoryListReq) GetDefId() string {
	if x != nil {
		return x.DefId
	}
	return ""
}

func (x *GetRunHistoryListReq) GetAscOrder() bool {
	if x != nil {
		return x.AscOrder
	}
	return false
}

func (x *GetRunHistoryListReq) GetPageIndex() int32 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *GetRunHistoryListReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetRunHistoryListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicRsp    *BasicRsp         `protobuf:"bytes,1,opt,name=basic_rsp,json=basicRsp,proto3" json:"basic_rsp,omitempty"`
	HistoryList []*TaskRunHistory `protobuf:"bytes,2,rep,name=history_list,json=historyList,proto3" json:"history_list,omitempty"`
}

func (x *GetRunHistoryListRsp) Reset() {
	*x = GetRunHistoryListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endpoint_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRunHistoryListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunHistoryListRsp) ProtoMessage() {}

func (x *GetRunHistoryListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunHistoryListRsp.ProtoReflect.Descriptor instead.
func (*GetRunHistoryListRsp) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{15}
}

func (x *GetRunHistoryListRsp) GetBasicRsp() *BasicRsp {
	if x != nil {
		return x.BasicRsp
	}
	return nil
}

func (x *GetRunHistoryListRsp) GetHistoryList() []*TaskRunHistory {
	if x != nil {
		return x.HistoryList
	}
	return nil
}

type TaskRunHistory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DefId    string `protobuf:"bytes,1,opt,name=def_id,json=defId,proto3" json:"def_id,omitempty"`           // [必填] 定时器定义ID
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                          // 定时器名称
	Output   string `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`                      // 执行结果
	RunTimer string `protobuf:"bytes,4,opt,name=run_timer,json=runTimer,proto3" json:"run_timer,omitempty"`  // 执行时间戳
	CostTime int64  `protobuf:"varint,5,opt,name=cost_time,json=costTime,proto3" json:"cost_time,omitempty"` // 执行耗时
	Status   string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                      // 当前状态
}

func (x *TaskRunHistory) Reset() {
	*x = TaskRunHistory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endpoint_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskRunHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRunHistory) ProtoMessage() {}

func (x *TaskRunHistory) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRunHistory.ProtoReflect.Descriptor instead.
func (*TaskRunHistory) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{16}
}

func (x *TaskRunHistory) GetDefId() string {
	if x != nil {
		return x.DefId
	}
	return ""
}

func (x *TaskRunHistory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskRunHistory) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *TaskRunHistory) GetRunTimer() string {
	if x != nil {
		return x.RunTimer
	}
	return ""
}

func (x *TaskRunHistory) GetCostTime() int64 {
	if x != nil {
		return x.CostTime
	}
	return 0
}

func (x *TaskRunHistory) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// CreateApp 创建APP
type CreateAppReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicReq *BasicReq `protobuf:"bytes,1,opt,name=basic_req,json=basicReq,proto3" json:"basic_req,omitempty"`
	Name     string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`       // 应用名
	Creator  string    `protobuf:"bytes,3,opt,name=creator,proto3" json:"creator,omitempty"` // 创建人
}

func (x *CreateAppReq) Reset() {
	*x = CreateAppReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endpoint_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAppReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppReq) ProtoMessage() {}

func (x *CreateAppReq) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppReq.ProtoReflect.Descriptor instead.
func (*CreateAppReq) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{17}
}

func (x *CreateAppReq) GetBasicReq() *BasicReq {
	if x != nil {
		return x.BasicReq
	}
	return nil
}

func (x *CreateAppReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAppReq) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

type CreateAppRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicRsp *BasicRsp `protobuf:"bytes,1,opt,name=basic_rsp,json=basicRsp,proto3" json:"basic_rsp,omitempty"`
}

func (x *CreateAppRsp) Reset() {
	*x = CreateAppRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endpoint_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAppRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppRsp) ProtoMessage() {}

func (x *CreateAppRsp) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppRsp.ProtoReflect.Descriptor instead.
func (*CreateAppRsp) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{18}
}

func (x *CreateAppRsp) GetBasicRsp() *BasicRsp {
	if x != nil {
		return x.BasicRsp
	}
	return nil
}

// DeleteApp 删除App
type DeleteAppReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicReq *BasicReq `protobuf:"bytes,1,opt,name=basic_req,json=basicReq,proto3" json:"basic_req,omitempty"`
	Name     string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // 应用名
}

func (x *DeleteAppReq) Reset() {
	*x = DeleteAppReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endpoint_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAppReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppReq) ProtoMessage() {}

func (x *DeleteAppReq) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppReq.ProtoReflect.Descriptor instead.
func (*DeleteAppReq) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteAppReq) GetBasicReq() *BasicReq {
	if x != nil {
		return x.BasicReq
	}
	return nil
}

func (x *DeleteAppReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteAppRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicRsp *BasicRsp `protobuf:"bytes,1,opt,name=basic_rsp,json=basicRsp,proto3" json:"basic_rsp,omitempty"`
}

func (x *DeleteAppRsp) Reset() {
	*x = DeleteAppRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endpoint_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAppRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppRsp) ProtoMessage() {}

func (x *DeleteAppRsp) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppRsp.ProtoReflect.Descriptor instead.
func (*DeleteAppRsp) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteAppRsp) GetBasicRsp() *BasicRsp {
	if x != nil {
		return x.BasicRsp
	}
	return nil
}

// GetAppList 获取App列表
type GetAppListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicReq  *BasicReq `protobuf:"bytes,1,opt,name=basic_req,json=basicReq,proto3" json:"basic_req,omitempty"`
	Name      string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                             // 应用名
	Creator   string    `protobuf:"bytes,3,opt,name=creator,proto3" json:"creator,omitempty"`                       // 创建人
	AscOrder  bool      `protobuf:"varint,4,opt,name=asc_order,json=ascOrder,proto3" json:"asc_order,omitempty"`    // 是否升序
	PageIndex int32     `protobuf:"varint,5,opt,name=page_index,json=pageIndex,proto3" json:"page_index,omitempty"` //
	PageSize  int32     `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`    //
}

func (x *GetAppListReq) Reset() {
	*x = GetAppListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endpoint_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAppListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppListReq) ProtoMessage() {}

func (x *GetAppListReq) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppListReq.ProtoReflect.Descriptor instead.
func (*GetAppListReq) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{21}
}

func (x *GetAppListReq) GetBasicReq() *BasicReq {
	if x != nil {
		return x.BasicReq
	}
	return nil
}

func (x *GetAppListReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetAppListReq) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *GetAppListReq) GetAscOrder() bool {
	if x != nil {
		return x.AscOrder
	}
	return false
}

func (x *GetAppListReq) GetPageIndex() int32 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *GetAppListReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetAppListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicRsp *BasicRsp  `protobuf:"bytes,1,opt,name=basic_rsp,json=basicRsp,proto3" json:"basic_rsp,omitempty"`
	AppList  []*AppInfo `protobuf:"bytes,2,rep,name=app_list,json=appList,proto3" json:"app_list,omitempty"` // 应用信息列表
}

func (x *GetAppListRsp) Reset() {
	*x = GetAppListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endpoint_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAppListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppListRsp) ProtoMessage() {}

func (x *GetAppListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppListRsp.ProtoReflect.Descriptor instead.
func (*GetAppListRsp) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{22}
}

func (x *GetAppListRsp) GetBasicRsp() *BasicRsp {
	if x != nil {
		return x.BasicRsp
	}
	return nil
}

func (x *GetAppListRsp) GetAppList() []*AppInfo {
	if x != nil {
		return x.AppList
	}
	return nil
}

type AppInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`          // 应用ID
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`       // 应用名
	Creator string `protobuf:"bytes,3,opt,name=creator,proto3" json:"creator,omitempty"` // 创建人
}

func (x *AppInfo) Reset() {
	*x = AppInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endpoint_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppInfo) ProtoMessage() {}

func (x *AppInfo) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppInfo.ProtoReflect.Descriptor instead.
func (*AppInfo) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{23}
}

func (x *AppInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AppInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppInfo) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

type BasicReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace   string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`     // 命名空间
	AccessToken string `protobuf:"bytes,2,opt,name=accessToken,proto3" json:"accessToken,omitempty"` // token
}

func (x *BasicReq) Reset() {
	*x = BasicReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endpoint_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BasicReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicReq) ProtoMessage() {}

func (x *BasicReq) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicReq.ProtoReflect.Descriptor instead.
func (*BasicReq) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{24}
}

func (x *BasicReq) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *BasicReq) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type BasicRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 错误码, 具体定义参考 https://cloud.google.com/natural-language/nl-whitelist/reference/rpc/google.rpc?hl=zh-cn
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *BasicRsp) Reset() {
	*x = BasicRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endpoint_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BasicRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicRsp) ProtoMessage() {}

func (x *BasicRsp) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicRsp.ProtoReflect.Descriptor instead.
func (*BasicRsp) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{25}
}

func (x *BasicRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BasicRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NotifyHttpParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"` // [必填]  HTTP方法如 POST、GET
	Url    string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`       // url HTTP 路径
	Header string `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"` // HTTP 请求头
	Body   string `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`     // 请求体
}

func (x *NotifyHttpParam) Reset() {
	*x = NotifyHttpParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endpoint_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyHttpParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyHttpParam) ProtoMessage() {}

func (x *NotifyHttpParam) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyHttpParam.ProtoReflect.Descriptor instead.
func (*NotifyHttpParam) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{26}
}

func (x *NotifyHttpParam) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *NotifyHttpParam) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *NotifyHttpParam) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *NotifyHttpParam) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_endpoint_proto protoreflect.FileDescriptor

var file_endpoint_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x22, 0x83, 0x04, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x2c, 0x0a, 0x09, 0x62, 0x61,
	0x73, 0x69, 0x63, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x52, 0x08,
	0x62, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x70, 0x70, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x70, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x72, 0x6f, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x72, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b,
	0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0a, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x64, 0x65, 0x6c, 0x61, 0x79, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x3f, 0x0a, 0x10, 0x6e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x5f, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x52, 0x70, 0x63, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x0e, 0x6e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x52, 0x70, 0x63, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x42, 0x0a, 0x11,
	0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x5f, 0x68, 0x74, 0x74, 0x70, 0x5f, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x48, 0x74, 0x74, 0x70, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52,
	0x0f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x48, 0x74, 0x74, 0x70, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x74,
	0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0b, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0d, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x2c, 0x0a, 0x12, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x65, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x94, 0x01,
	0x0a, 0x0e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x70, 0x63, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x70, 0x63, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x70, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x65, 0x5f,
	0x65, 0x6e, 0x76, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x61, 0x6c, 0x6c, 0x65,
	0x65, 0x45, 0x6e, 0x76, 0x22, 0x52, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x72, 0x52, 0x73, 0x70, 0x12, 0x2c, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f,
	0x72, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x69, 0x6d, 0x65,
	0x72, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x73, 0x70, 0x52, 0x08, 0x62, 0x61, 0x73, 0x69,
	0x63, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x55, 0x0a, 0x0e, 0x45, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x2c, 0x0a, 0x09, 0x62, 0x61,
	0x73, 0x69, 0x63, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x52, 0x08,
	0x62, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x65, 0x66, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x65, 0x66, 0x49, 0x64, 0x22,
	0x3e, 0x0a, 0x0e, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x52, 0x73,
	0x70, 0x12, 0x2c, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x72, 0x73, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e, 0x42, 0x61, 0x73,
	0x69, 0x63, 0x52, 0x73, 0x70, 0x52, 0x08, 0x62, 0x61, 0x73, 0x69, 0x63, 0x52, 0x73, 0x70, 0x22,
	0x56, 0x0a, 0x0f, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x12, 0x2c, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x72, 0x65, 0x71, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e, 0x42, 0x61,
	0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x52, 0x08, 0x62, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71,
	0x12, 0x15, 0x0a, 0x06, 0x64, 0x65, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x64, 0x65, 0x66, 0x49, 0x64, 0x22, 0x3f, 0x0a, 0x0f, 0x44, 0x69, 0x73, 0x61, 0x62,
	0x6c, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x52, 0x73, 0x70, 0x12, 0x2c, 0x0a, 0x09, 0x62, 0x61,
	0x73, 0x69, 0x63, 0x5f, 0x72, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x73, 0x70, 0x52, 0x08,
	0x62, 0x61, 0x73, 0x69, 0x63, 0x52, 0x73, 0x70, 0x22, 0x55, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x72, 0x44, 0x65, 0x66, 0x52, 0x65, 0x71, 0x12, 0x2c, 0x0a, 0x09, 0x62, 0x61,
	0x73, 0x69, 0x63, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x52, 0x08,
	0x62, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x65, 0x66, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x65, 0x66, 0x49, 0x64, 0x22,
	0x6c, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x44, 0x65, 0x66, 0x52, 0x73,
	0x70, 0x12, 0x2c, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x72, 0x73, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e, 0x42, 0x61, 0x73,
	0x69, 0x63, 0x52, 0x73, 0x70, 0x52, 0x08, 0x62, 0x61, 0x73, 0x69, 0x63, 0x52, 0x73, 0x70, 0x12,
	0x2c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x5f, 0x64, 0x65, 0x66, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x72,
	0x44, 0x65, 0x66, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x44, 0x65, 0x66, 0x22, 0x7e, 0x0a,
	0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x44, 0x65, 0x66, 0x52,
	0x65, 0x71, 0x12, 0x2c, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x72, 0x65, 0x71, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e, 0x42, 0x61,
	0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x52, 0x08, 0x62, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71,
	0x12, 0x15, 0x0a, 0x06, 0x64, 0x65, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x64, 0x65, 0x66, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x70, 0x70, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x70, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x41, 0x0a,
	0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x44, 0x65, 0x66, 0x52,
	0x73, 0x70, 0x12, 0x2c, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x72, 0x73, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e, 0x42, 0x61,
	0x73, 0x69, 0x63, 0x52, 0x73, 0x70, 0x52, 0x08, 0x62, 0x61, 0x73, 0x69, 0x63, 0x52, 0x73, 0x70,
	0x22, 0xb6, 0x02, 0x0a, 0x08, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x44, 0x65, 0x66, 0x12, 0x15, 0x0a,
	0x06, 0x64, 0x65, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64,
	0x65, 0x66, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x72, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x63, 0x72, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x72,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x61,
	0x79, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x3f, 0x0a, 0x10, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x5f,
	0x72, 0x70, 0x63, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x70,
	0x63, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x0e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x70,
	0x63, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x70, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x72, 0x44, 0x65, 0x66, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x2c, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63,
	0x52, 0x65, 0x71, 0x52, 0x08, 0x62, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x72, 0x0a, 0x12, 0x47,
	0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x44, 0x65, 0x66, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73,
	0x70, 0x12, 0x2c, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x72, 0x73, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e, 0x42, 0x61, 0x73,
	0x69, 0x63, 0x52, 0x73, 0x70, 0x52, 0x08, 0x62, 0x61, 0x73, 0x69, 0x63, 0x52, 0x73, 0x70, 0x12,
	0x2e, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x5f, 0x64, 0x65, 0x66, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x72, 0x44, 0x65, 0x66, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x44, 0x65, 0x66, 0x73, 0x22,
	0xb4, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x2c, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x69,
	0x63, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x69,
	0x6d, 0x65, 0x72, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x52, 0x08, 0x62, 0x61,
	0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x65, 0x66, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x65, 0x66, 0x49, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x61, 0x73, 0x63, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x61, 0x73, 0x63, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61,
	0x67, 0x65, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x70, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67,
	0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61,
	0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x7e, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6e,
	0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x2c,
	0x0a, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x72, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52,
	0x73, 0x70, 0x52, 0x08, 0x62, 0x61, 0x73, 0x69, 0x63, 0x52, 0x73, 0x70, 0x12, 0x38, 0x0a, 0x0c,
	0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52,
	0x75, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x0b, 0x68, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x22, 0xa5, 0x01, 0x0a, 0x0e, 0x54, 0x61, 0x73, 0x6b, 0x52,
	0x75, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x65, 0x66,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x65, 0x66, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x72, 0x75, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x72, 0x75, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x73,
	0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x6f,
	0x73, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x6a,
	0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x12, 0x2c,
	0x0a, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52,
	0x65, 0x71, 0x52, 0x08, 0x62, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x3c, 0x0a, 0x0c, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x52, 0x73, 0x70, 0x12, 0x2c, 0x0a, 0x09, 0x62, 0x61,
	0x73, 0x69, 0x63, 0x5f, 0x72, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x73, 0x70, 0x52, 0x08,
	0x62, 0x61, 0x73, 0x69, 0x63, 0x52, 0x73, 0x70, 0x22, 0x50, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x12, 0x2c, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x69,
	0x63, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x69,
	0x6d, 0x65, 0x72, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x52, 0x08, 0x62, 0x61,
	0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3c, 0x0a, 0x0c, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x41, 0x70, 0x70, 0x52, 0x73, 0x70, 0x12, 0x2c, 0x0a, 0x09, 0x62, 0x61,
	0x73, 0x69, 0x63, 0x5f, 0x72, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x73, 0x70, 0x52, 0x08,
	0x62, 0x61, 0x73, 0x69, 0x63, 0x52, 0x73, 0x70, 0x22, 0xc4, 0x01, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x41, 0x70, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x2c, 0x0a, 0x09, 0x62, 0x61,
	0x73, 0x69, 0x63, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x52, 0x08,
	0x62, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x73, 0x63, 0x5f, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x73, 0x63, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22,
	0x68, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70,
	0x12, 0x2c, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x72, 0x73, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e, 0x42, 0x61, 0x73, 0x69,
	0x63, 0x52, 0x73, 0x70, 0x52, 0x08, 0x62, 0x61, 0x73, 0x69, 0x63, 0x52, 0x73, 0x70, 0x12, 0x29,
	0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x07, 0x61, 0x70, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x47, 0x0a, 0x07, 0x41, 0x70, 0x70,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x6f, 0x72, 0x22, 0x4a, 0x0a, 0x08, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x12, 0x1c,
	0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x38,
	0x0a, 0x08, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x67, 0x0a, 0x0f, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x48, 0x74, 0x74, 0x70, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x6d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x32, 0x87, 0x05, 0x0a, 0x08, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x3b,
	0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x12, 0x15, 0x2e,
	0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x52, 0x73, 0x70, 0x12, 0x3b, 0x0a, 0x0b, 0x45,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x12, 0x15, 0x2e, 0x74, 0x69, 0x6d,
	0x65, 0x72, 0x2e, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x1a, 0x15, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x72, 0x52, 0x73, 0x70, 0x12, 0x3e, 0x0a, 0x0c, 0x44, 0x69, 0x73, 0x61,
	0x62, 0x6c, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x12, 0x16, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x72,
	0x2e, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x1a, 0x16, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x72, 0x52, 0x73, 0x70, 0x12, 0x3b, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x72, 0x44, 0x65, 0x66, 0x12, 0x15, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e,
	0x47, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x44, 0x65, 0x66, 0x52, 0x65, 0x71, 0x1a, 0x15,
	0x2e, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x44,
	0x65, 0x66, 0x52, 0x73, 0x70, 0x12, 0x44, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x72, 0x44, 0x65, 0x66, 0x12, 0x18, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x44, 0x65, 0x66, 0x52, 0x65,
	0x71, 0x1a, 0x18, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x72, 0x44, 0x65, 0x66, 0x52, 0x73, 0x70, 0x12, 0x47, 0x0a, 0x0f, 0x47,
	0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x44, 0x65, 0x66, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x19,
	0x2e, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x44,
	0x65, 0x66, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x74, 0x69, 0x6d, 0x65,
	0x72, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x44, 0x65, 0x66, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x73, 0x70, 0x12, 0x4d, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6e, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1b, 0x2e, 0x74, 0x69, 0x6d, 0x65,
	0x72, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e, 0x47,
	0x65, 0x74, 0x52, 0x75, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x73, 0x70, 0x12, 0x35, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70,
	0x12, 0x13, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41,
	0x70, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x52, 0x73, 0x70, 0x12, 0x35, 0x0a, 0x09, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x41, 0x70, 0x70, 0x12, 0x13, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x74,
	0x69, 0x6d, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x70, 0x70, 0x52, 0x73,
	0x70, 0x12, 0x38, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x14, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x70, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x42, 0x47, 0x0a, 0x13, 0x69,
	0x6f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x66, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x74, 0x69, 0x6d,
	0x65, 0x72, 0x42, 0x0a, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x22, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e,
	0x6f, 0x72, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x66, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_endpoint_proto_rawDescOnce sync.Once
	file_endpoint_proto_rawDescData = file_endpoint_proto_rawDesc
)

func file_endpoint_proto_rawDescGZIP() []byte {
	file_endpoint_proto_rawDescOnce.Do(func() {
		file_endpoint_proto_rawDescData = protoimpl.X.CompressGZIP(file_endpoint_proto_rawDescData)
	})
	return file_endpoint_proto_rawDescData
}

var file_endpoint_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_endpoint_proto_goTypes = []interface{}{
	(*CreateTimerReq)(nil),       // 0: timer.CreateTimerReq
	(*NotifyRpcParam)(nil),       // 1: timer.NotifyRpcParam
	(*CreateTimerRsp)(nil),       // 2: timer.CreateTimerRsp
	(*EnableTimerReq)(nil),       // 3: timer.EnableTimerReq
	(*EnableTimerRsp)(nil),       // 4: timer.EnableTimerRsp
	(*DisableTimerReq)(nil),      // 5: timer.DisableTimerReq
	(*DisableTimerRsp)(nil),      // 6: timer.DisableTimerRsp
	(*GetTimerDefReq)(nil),       // 7: timer.GetTimerDefReq
	(*GetTimerDefRsp)(nil),       // 8: timer.GetTimerDefRsp
	(*DeleteTimerDefReq)(nil),    // 9: timer.DeleteTimerDefReq
	(*DeleteTimerDefRsp)(nil),    // 10: timer.DeleteTimerDefRsp
	(*TimerDef)(nil),             // 11: timer.TimerDef
	(*GetTimerDefListReq)(nil),   // 12: timer.GetTimerDefListReq
	(*GetTimerDefListRsp)(nil),   // 13: timer.GetTimerDefListRsp
	(*GetRunHistoryListReq)(nil), // 14: timer.GetRunHistoryListReq
	(*GetRunHistoryListRsp)(nil), // 15: timer.GetRunHistoryListRsp
	(*TaskRunHistory)(nil),       // 16: timer.TaskRunHistory
	(*CreateAppReq)(nil),         // 17: timer.CreateAppReq
	(*CreateAppRsp)(nil),         // 18: timer.CreateAppRsp
	(*DeleteAppReq)(nil),         // 19: timer.DeleteAppReq
	(*DeleteAppRsp)(nil),         // 20: timer.DeleteAppRsp
	(*GetAppListReq)(nil),        // 21: timer.GetAppListReq
	(*GetAppListRsp)(nil),        // 22: timer.GetAppListRsp
	(*AppInfo)(nil),              // 23: timer.AppInfo
	(*BasicReq)(nil),             // 24: timer.BasicReq
	(*BasicRsp)(nil),             // 25: timer.BasicRsp
	(*NotifyHttpParam)(nil),      // 26: timer.NotifyHttpParam
}
var file_endpoint_proto_depIdxs = []int32{
	24, // 0: timer.CreateTimerReq.basic_req:type_name -> timer.BasicReq
	1,  // 1: timer.CreateTimerReq.notify_rpc_param:type_name -> timer.NotifyRpcParam
	26, // 2: timer.CreateTimerReq.notify_http_param:type_name -> timer.NotifyHttpParam
	25, // 3: timer.CreateTimerRsp.basic_rsp:type_name -> timer.BasicRsp
	24, // 4: timer.EnableTimerReq.basic_req:type_name -> timer.BasicReq
	25, // 5: timer.EnableTimerRsp.basic_rsp:type_name -> timer.BasicRsp
	24, // 6: timer.DisableTimerReq.basic_req:type_name -> timer.BasicReq
	25, // 7: timer.DisableTimerRsp.basic_rsp:type_name -> timer.BasicRsp
	24, // 8: timer.GetTimerDefReq.basic_req:type_name -> timer.BasicReq
	25, // 9: timer.GetTimerDefRsp.basic_rsp:type_name -> timer.BasicRsp
	11, // 10: timer.GetTimerDefRsp.timer_def:type_name -> timer.TimerDef
	24, // 11: timer.DeleteTimerDefReq.basic_req:type_name -> timer.BasicReq
	25, // 12: timer.DeleteTimerDefRsp.basic_rsp:type_name -> timer.BasicRsp
	1,  // 13: timer.TimerDef.notify_rpc_param:type_name -> timer.NotifyRpcParam
	24, // 14: timer.GetTimerDefListReq.basic_req:type_name -> timer.BasicReq
	25, // 15: timer.GetTimerDefListRsp.basic_rsp:type_name -> timer.BasicRsp
	11, // 16: timer.GetTimerDefListRsp.timer_defs:type_name -> timer.TimerDef
	24, // 17: timer.GetRunHistoryListReq.basic_req:type_name -> timer.BasicReq
	25, // 18: timer.GetRunHistoryListRsp.basic_rsp:type_name -> timer.BasicRsp
	16, // 19: timer.GetRunHistoryListRsp.history_list:type_name -> timer.TaskRunHistory
	24, // 20: timer.CreateAppReq.basic_req:type_name -> timer.BasicReq
	25, // 21: timer.CreateAppRsp.basic_rsp:type_name -> timer.BasicRsp
	24, // 22: timer.DeleteAppReq.basic_req:type_name -> timer.BasicReq
	25, // 23: timer.DeleteAppRsp.basic_rsp:type_name -> timer.BasicRsp
	24, // 24: timer.GetAppListReq.basic_req:type_name -> timer.BasicReq
	25, // 25: timer.GetAppListRsp.basic_rsp:type_name -> timer.BasicRsp
	23, // 26: timer.GetAppListRsp.app_list:type_name -> timer.AppInfo
	0,  // 27: timer.Endpoint.CreateTimer:input_type -> timer.CreateTimerReq
	3,  // 28: timer.Endpoint.EnableTimer:input_type -> timer.EnableTimerReq
	5,  // 29: timer.Endpoint.DisableTimer:input_type -> timer.DisableTimerReq
	7,  // 30: timer.Endpoint.GetTimerDef:input_type -> timer.GetTimerDefReq
	9,  // 31: timer.Endpoint.DeleteTimerDef:input_type -> timer.DeleteTimerDefReq
	12, // 32: timer.Endpoint.GetTimerDefList:input_type -> timer.GetTimerDefListReq
	14, // 33: timer.Endpoint.GetRunHistoryList:input_type -> timer.GetRunHistoryListReq
	17, // 34: timer.Endpoint.CreateApp:input_type -> timer.CreateAppReq
	19, // 35: timer.Endpoint.DeleteApp:input_type -> timer.DeleteAppReq
	21, // 36: timer.Endpoint.GetAppList:input_type -> timer.GetAppListReq
	2,  // 37: timer.Endpoint.CreateTimer:output_type -> timer.CreateTimerRsp
	4,  // 38: timer.Endpoint.EnableTimer:output_type -> timer.EnableTimerRsp
	6,  // 39: timer.Endpoint.DisableTimer:output_type -> timer.DisableTimerRsp
	8,  // 40: timer.Endpoint.GetTimerDef:output_type -> timer.GetTimerDefRsp
	10, // 41: timer.Endpoint.DeleteTimerDef:output_type -> timer.DeleteTimerDefRsp
	13, // 42: timer.Endpoint.GetTimerDefList:output_type -> timer.GetTimerDefListRsp
	15, // 43: timer.Endpoint.GetRunHistoryList:output_type -> timer.GetRunHistoryListRsp
	18, // 44: timer.Endpoint.CreateApp:output_type -> timer.CreateAppRsp
	20, // 45: timer.Endpoint.DeleteApp:output_type -> timer.DeleteAppRsp
	22, // 46: timer.Endpoint.GetAppList:output_type -> timer.GetAppListRsp
	37, // [37:47] is the sub-list for method output_type
	27, // [27:37] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_endpoint_proto_init() }
func file_endpoint_proto_init() {
	if File_endpoint_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_endpoint_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTimerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_endpoint_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyRpcParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_endpoint_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTimerRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_endpoint_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnableTimerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_endpoint_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnableTimerRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_endpoint_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisableTimerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_endpoint_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisableTimerRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_endpoint_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTimerDefReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_endpoint_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTimerDefRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_endpoint_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTimerDefReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_endpoint_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTimerDefRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_endpoint_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimerDef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_endpoint_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTimerDefListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_endpoint_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTimerDefListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_endpoint_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRunHistoryListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_endpoint_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRunHistoryListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_endpoint_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskRunHistory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_endpoint_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAppReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_endpoint_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAppRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_endpoint_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAppReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_endpoint_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAppRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_endpoint_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAppListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_endpoint_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAppListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_endpoint_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_endpoint_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BasicReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_endpoint_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BasicRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_endpoint_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyHttpParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_endpoint_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_endpoint_proto_goTypes,
		DependencyIndexes: file_endpoint_proto_depIdxs,
		MessageInfos:      file_endpoint_proto_msgTypes,
	}.Build()
	File_endpoint_proto = out.File
	file_endpoint_proto_rawDesc = nil
	file_endpoint_proto_goTypes = nil
	file_endpoint_proto_depIdxs = nil
}
