// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: faas_endpoint.proto

package faas

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Call 调用函数
type CallReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicReq *BasicReq `protobuf:"bytes,1,opt,name=basicReq,proto3" json:"basicReq,omitempty"`
	Function string    `protobuf:"bytes,2,opt,name=function,proto3" json:"function,omitempty"` // [必填] 方法名
	Input    string    `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`       // [选填] 传入数据
}

func (x *CallReq) Reset() {
	*x = CallReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_faas_endpoint_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallReq) ProtoMessage() {}

func (x *CallReq) ProtoReflect() protoreflect.Message {
	mi := &file_faas_endpoint_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallReq.ProtoReflect.Descriptor instead.
func (*CallReq) Descriptor() ([]byte, []int) {
	return file_faas_endpoint_proto_rawDescGZIP(), []int{0}
}

func (x *CallReq) GetBasicReq() *BasicReq {
	if x != nil {
		return x.BasicReq
	}
	return nil
}

func (x *CallReq) GetFunction() string {
	if x != nil {
		return x.Function
	}
	return ""
}

func (x *CallReq) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type CallRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicRsp *BasicRsp `protobuf:"bytes,1,opt,name=basicRsp,proto3" json:"basicRsp,omitempty"`
	Output   string    `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *CallRsp) Reset() {
	*x = CallRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_faas_endpoint_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRsp) ProtoMessage() {}

func (x *CallRsp) ProtoReflect() protoreflect.Message {
	mi := &file_faas_endpoint_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRsp.ProtoReflect.Descriptor instead.
func (*CallRsp) Descriptor() ([]byte, []int) {
	return file_faas_endpoint_proto_rawDescGZIP(), []int{1}
}

func (x *CallRsp) GetBasicRsp() *BasicRsp {
	if x != nil {
		return x.BasicRsp
	}
	return nil
}

func (x *CallRsp) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type BasicReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace   string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`     // 命名空间
	AccessToken string `protobuf:"bytes,2,opt,name=accessToken,proto3" json:"accessToken,omitempty"` // token
}

func (x *BasicReq) Reset() {
	*x = BasicReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_faas_endpoint_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BasicReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicReq) ProtoMessage() {}

func (x *BasicReq) ProtoReflect() protoreflect.Message {
	mi := &file_faas_endpoint_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicReq.ProtoReflect.Descriptor instead.
func (*BasicReq) Descriptor() ([]byte, []int) {
	return file_faas_endpoint_proto_rawDescGZIP(), []int{2}
}

func (x *BasicReq) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *BasicReq) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type BasicRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 错误码, 具体定义参考 https://cloud.google.com/natural-language/nl-whitelist/reference/rpc/google.rpc?hl=zh-cn
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *BasicRsp) Reset() {
	*x = BasicRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_faas_endpoint_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BasicRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicRsp) ProtoMessage() {}

func (x *BasicRsp) ProtoReflect() protoreflect.Message {
	mi := &file_faas_endpoint_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicRsp.ProtoReflect.Descriptor instead.
func (*BasicRsp) Descriptor() ([]byte, []int) {
	return file_faas_endpoint_proto_rawDescGZIP(), []int{3}
}

func (x *BasicRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BasicRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_faas_endpoint_proto protoreflect.FileDescriptor

var file_faas_endpoint_proto_rawDesc = []byte{
	0x0a, 0x13, 0x66, 0x61, 0x61, 0x73, 0x5f, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x66, 0x61, 0x61, 0x73, 0x22, 0x67, 0x0a, 0x07, 0x43,
	0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x2a, 0x0a, 0x08, 0x62, 0x61, 0x73, 0x69, 0x63, 0x52,
	0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x66, 0x61, 0x61, 0x73, 0x2e,
	0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x52, 0x08, 0x62, 0x61, 0x73, 0x69, 0x63, 0x52,
	0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69,
	0x6e, 0x70, 0x75, 0x74, 0x22, 0x4d, 0x0a, 0x07, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x73, 0x70, 0x12,
	0x2a, 0x0a, 0x08, 0x62, 0x61, 0x73, 0x69, 0x63, 0x52, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x66, 0x61, 0x61, 0x73, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x73,
	0x70, 0x52, 0x08, 0x62, 0x61, 0x73, 0x69, 0x63, 0x52, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x6f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x22, 0x4a, 0x0a, 0x08, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x12,
	0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22,
	0x38, 0x0a, 0x08, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x2c, 0x0a, 0x04, 0x46, 0x61, 0x61,
	0x73, 0x12, 0x24, 0x0a, 0x04, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x0d, 0x2e, 0x66, 0x61, 0x61, 0x73,
	0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x66, 0x61, 0x61, 0x73, 0x2e,
	0x43, 0x61, 0x6c, 0x6c, 0x52, 0x73, 0x70, 0x42, 0x44, 0x0a, 0x12, 0x69, 0x6f, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x66, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x66, 0x61, 0x61, 0x73, 0x42, 0x09, 0x46,
	0x61, 0x61, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x21, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x66, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x66, 0x61, 0x61, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_faas_endpoint_proto_rawDescOnce sync.Once
	file_faas_endpoint_proto_rawDescData = file_faas_endpoint_proto_rawDesc
)

func file_faas_endpoint_proto_rawDescGZIP() []byte {
	file_faas_endpoint_proto_rawDescOnce.Do(func() {
		file_faas_endpoint_proto_rawDescData = protoimpl.X.CompressGZIP(file_faas_endpoint_proto_rawDescData)
	})
	return file_faas_endpoint_proto_rawDescData
}

var file_faas_endpoint_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_faas_endpoint_proto_goTypes = []interface{}{
	(*CallReq)(nil),  // 0: faas.CallReq
	(*CallRsp)(nil),  // 1: faas.CallRsp
	(*BasicReq)(nil), // 2: faas.BasicReq
	(*BasicRsp)(nil), // 3: faas.BasicRsp
}
var file_faas_endpoint_proto_depIdxs = []int32{
	2, // 0: faas.CallReq.basicReq:type_name -> faas.BasicReq
	3, // 1: faas.CallRsp.basicRsp:type_name -> faas.BasicRsp
	0, // 2: faas.Faas.Call:input_type -> faas.CallReq
	1, // 3: faas.Faas.Call:output_type -> faas.CallRsp
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_faas_endpoint_proto_init() }
func file_faas_endpoint_proto_init() {
	if File_faas_endpoint_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_faas_endpoint_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_faas_endpoint_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_faas_endpoint_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BasicReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_faas_endpoint_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BasicRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_faas_endpoint_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_faas_endpoint_proto_goTypes,
		DependencyIndexes: file_faas_endpoint_proto_depIdxs,
		MessageInfos:      file_faas_endpoint_proto_msgTypes,
	}.Build()
	File_faas_endpoint_proto = out.File
	file_faas_endpoint_proto_rawDesc = nil
	file_faas_endpoint_proto_goTypes = nil
	file_faas_endpoint_proto_depIdxs = nil
}
