// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package faas

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// FaasClient is the client API for Faas service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FaasClient interface {
	Call(ctx context.Context, in *CallReq, opts ...grpc.CallOption) (*CallRsp, error)
}

type faasClient struct {
	cc grpc.ClientConnInterface
}

func NewFaasClient(cc grpc.ClientConnInterface) FaasClient {
	return &faasClient{cc}
}

func (c *faasClient) Call(ctx context.Context, in *CallReq, opts ...grpc.CallOption) (*CallRsp, error) {
	out := new(CallRsp)
	err := c.cc.Invoke(ctx, "/faas.Faas/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FaasServer is the server API for Faas service.
// All implementations must embed UnimplementedFaasServer
// for forward compatibility
type FaasServer interface {
	Call(context.Context, *CallReq) (*CallRsp, error)
	mustEmbedUnimplementedFaasServer()
}

// UnimplementedFaasServer must be embedded to have forward compatible implementations.
type UnimplementedFaasServer struct {
}

func (UnimplementedFaasServer) Call(context.Context, *CallReq) (*CallRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedFaasServer) mustEmbedUnimplementedFaasServer() {}

// UnsafeFaasServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FaasServer will
// result in compilation errors.
type UnsafeFaasServer interface {
	mustEmbedUnimplementedFaasServer()
}

func RegisterFaasServer(s grpc.ServiceRegistrar, srv FaasServer) {
	s.RegisterService(&_Faas_serviceDesc, srv)
}

func _Faas_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaasServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/faas.Faas/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaasServer).Call(ctx, req.(*CallReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Faas_serviceDesc = grpc.ServiceDesc{
	ServiceName: "faas.Faas",
	HandlerType: (*FaasServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _Faas_Call_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "faas_endpoint.proto",
}
