// Code generated by 'yaegi extract github.com/bitly/go-simplejson'. DO NOT EDIT.

package golang

import (
	"github.com/bitly/go-simplejson"
	"reflect"
)

func init() {
	Symbols["github.com/bitly/go-simplejson/simplejson"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"New":           reflect.ValueOf(simplejson.New),
		"NewFromReader": reflect.ValueOf(simplejson.NewFromReader),
		"NewJson":       reflect.ValueOf(simplejson.NewJson),
		"Version":       reflect.ValueOf(simplejson.Version),

		// type definitions
		"Json": reflect.ValueOf((*simplejson.Json)(nil)),
	}
}
